[benchmark-framework]
frameworks = [
    'mindquantum',
    'qulacs',
]


[framework.mindquantum]
    [framework.mindquantum.benchmark_qft]
        platform = ['cpu']
        qubit_min = 15
        qubit_max = 29

    [framework.mindquantum.benchmark_4_regular_qaoa]
        platform = ['cpu']
        qubit_min = 15
        qubit_max = 27

[framework.qulacs]
    [framework.qulacs.benchmark_qft]
        platform = ['cpu']
        qubit_min = 15
        qubit_max = 29
    [framework.qulacs.benchmark_4_regular_qaoa]
        platform = ['cpu']
        qubit_min = 15
        qubit_max = 27
